server:
  port: 8080
spring:
  application:
    name: customerservice
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: 'postgresql'
    password: 'admin'
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'