server:
  port: 8082

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: 'postgresql'
    password: 'admin'
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'

  config:
    import: "optional:configserver:cloud-config-server"
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: cloud-config-server
#  sql:
#    init:
#      mode: always


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true